@ECHO OFF

IF "%~4"=="" EXIT 1

SETLOCAL
SET DISTRIBUTION=%1
SET VERSION=%2
SET SOURCE=%3
SET TOKEN=%4

ECHO.
ECHO Preparing to deploy...
ECHO Distribution: %DISTRIBUTION%
ECHO Version: %VERSION%
ECHO Source: %SOURCE%
ECHO.

dotnet nuget push "%DISTRIBUTION%\bin\Release\%DISTRIBUTION%.%VERSION%.nupkg" --source "%SOURCE%" --api-key %TOKEN%
ENDLOCAL

TIMEOUT 30

EXIT 0